#%RAML 1.0 Library

usage: |
  provides a set of resusable data types that extend common types
  to add linking and hypermedia to REST APIs

uses:
    metadata: metadata-types.raml
    common: common-types.raml

types:

  Link:
    type: object
    additionalProperties: false
    properties:
      href:
        type: common.url
      title?:
        type: string

  CollectionPagingLinks:
    type: object
    additionalProperties: false
    properties:
      self:
        type: Link
      first?:
        type: Link
      prev?:
        type: Link
      next?:
        type: Link
      last?:
        type: Link

  CollectionResponse:
    type: metadata.DefaultResponse
    additionalProperties: false
    properties:
      _meta: metadata.ResponseMetadata
      _links: CollectionPagingLinks

  ErrorResponse:
    type: metadata.DefaultResponse
    additionalProperties: false
