#%RAML 1.0 Library

usage: |
  provides a resuable set of data types that can used and extended
  to implement queries and response objects for RESTful APIs

uses:
  common: common-types.raml

types:

  collectionTotalItems:
    type: integer
    minimum: 0

  pagingOffset:
    type: integer
    minimum: 0
    default: 0

  pagingLimit:
    type: integer
    minimum: 5
    default: 10
    maximum: 20

  SortingSortKey:
    type: string[]

  Message:
    type: object
    additionalProperties: false
    properties:
      severity:
        type: string
        enum: [ INFO, WARN, ERROR, FATAL ]
      code: string
      description: string

  ResponseMetadata:
    type: object
    additionalProperties: false
    properties:
      messages:
        type: Message[]

  CollectionResponseMetadata:
    type: ResponseMetadata
    additionalProperties: false
    properties:
      totalItems?: collectionTotalItems
      offset?: pagingOffset
      limit?: pagingLimit
      sortBy?: string[]

  DefaultResponse:
    type: object
    additionalProperties: false
    properties:
      _meta: ResponseMetadata

  CollectionResponse:
    type: DefaultResponse
    additionalProperties: false
    properties:
      _meta: CollectionResponseMetadata

  ErrorResponse:
    type: DefaultResponse
    additionalProperties: false
